const itemNames = [
    "Watch", "Shoe", "Sunglasses", "Cold Drink", "Pen",
    // "Bag", "Shirt", "Hat", "Glasses", "Laptop",
    // "Phone", "Headphone", "Backpack", "Guitar", "Coffee",
    // "Chair", "Flower", "Book", "Car", "Bike",
    // "Television", "Desk", "Keyboard", "Mouse", "Table",
    // "Plant", "Camera", "Ring", "Necklace", "Earring",
    // "Dress", "Jean", "Jacket", "Scarf", "Glove",
    // "Boot", "Sandal", "Sneaker", "Backpack", "Suitcase",
    // "Sweater", "Hat", "Umbrella", "Socks", "Tie",
    // "Candle", "Mirror", "Painting", "Clock", "Vase",
    // "Chair", "Sofa", "Couch", "Table", "Lamp",
    // "Dining Table", "Cutlery", "Plate", "Cup", "Bowl",
    // "Bed", "Pillow", "Blanket", "Mattress", "Duvet",
    // "Curtains", "Towel", "Toothbrush", "Soap", "Shampoo",
    // "Toilet Paper", "Tissue Box", "Trash Can", "Broom", "Mop",
    // "Refrigerator", "Oven", "Microwave", "Blender", "Coffee Maker",
    // "Pot", "Pan", "Knife Set", "Cutting Board", "Frying Pan",
    // "Washing Machine", "Vacuum Cleaner", "Iron", "Hair Dryer", "Toaster",
    // "Dishwasher", "Food Processor", "Mixing Bowl", "Cookie Jar", "Dining Chair",
    // "Cabinet", "Bookshelf", "Dresser", "Nightstand", "Desk Chair",
    // "Guitar Case", "Drum Kit", "Violin", "Trumpet", "Piano",
    // "Luggage", "Rug", "Couch", "Basket", "Sculpture",
    // "Mirror", "Easel", "Desk Lamp", "Chest", "Rocking Chair",
    // "Vanity", "Credenza", "Stool", "Futon", "Ottoman",
    // "Bean Bag", "Hammock", "Fireplace", "Wall Art", "Cabin",
    // "Bookcase", "Storage", "Armchair", "Chandelier", "Ceiling Fan",
    // "Dresser", "Nightstand", "Desk Chair", "Guitar Case", "Drum Kit",
    // "Violin", "Trumpet", "Piano", "Luggage", "Rug",
    // "Couch", "Basket", "Sculpture", "Mirror", "Easel",
    // "Desk Lamp", "Chest", "Rocking Chair", "Vanity", "Credenza",
    // "Stool", "Futon", "Ottoman", "Bean Bag", "Hammock",
    // "Fireplace", "Wall Art", "Cabin", "Bookcase", "Storage",
    // "Armchair", "Chandelier", "Ceiling Fan", "Desk", "Sofa",
    // "Chair", "Table", "Lamp", "Dining Table", "Cutlery",
    // "Plate", "Cup", "Bowl", "Bed", "Pillow",
    // "Blanket", "Mattress", "Duvet", "Curtain", "Towel",
    // "Toothbrush", "Soap", "Shampoo", "Toilet Paper", "Tissue Box",
    // "Trash Can", "Broom", "Mop", "Refrigerator", "Oven",
    // "Microwave", "Blender", "Coffee Maker", "Pot", "Pan",
    // "Knife Set", "Cutting Board", "Frying Pan", "Tablecloth", "Napkin"
];


export const Fifth_Task_ShopPage_API = itemNames.map((itemName, index) => ({
    id: index + 1,
    name: itemName,
    image1: `https://source.unsplash.com/500x250/?${itemName}`,
    image2: `https://source.unsplash.com/500x250/?${itemName}s`,
    title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam, ducimus.",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque ipsum expedita ab, similique repellat odio ipsam quam nisi, quaerat consequatur fugit culpa perferendis nesciunt dolor mollitia eligendi, vero odit eius."
}));
